### PR TITLE
Check archive entry directory

### PR DESCRIPTION
**Pull request by erikkemperman**

### CODE REVIEW

**Comment by jecollins** [comment]
Seems straightforward. Thanks.

**Comment by erikkemperman** [comment]
Just now it occurred to me: can we assume forward slash separator even on windows? Surely it's part of the TAR spec, right?

**Comment by jecollins** [comment]
I have no idea. I assume it's part of the tar spec, but all I can find is references to POSIX specs. That would indicate that it uses the unix conventions. But these archives are created by the TS, not the simulator or viz, so I don't think we need to worry about it until someone decides the TS has to be supported on Windows. I am not in favor of putting our time/resources into meeting such a commitment.

**Comment by erikkemperman** [comment]
I expect that if one creates a tar on Windows (if that's even supported) it will also have to use forward slashes:

http://www.gnu.org/software/tar/manual/html_node/Standard.html (search for "slash")

**Pull request merged**
